from django.db import models
from django.contrib.auth.models import User
from payu.models import PayuDetails

#
# class Transaction(models.Model):
#     """Maintain user transaction details"""
#     TRANS_MODE = (('online', 'Online'), ('offline', 'Offline'))
#     POST_TYPE = (('banner', 'Banner'), ('event', 'Event'))
#     user = models.ForeignKey(User)
#     transaction_mode = models.CharField(
#         max_length=50,
#         choices=TRANS_MODE,
#         help_text='User used transaction type',
#         verbose_name='Transaction',
#         )
#     post_type = models.CharField(
#         max_length=50,
#         choices=POST_MODE,
#         help_text='Transaction for Banner or Event'
#     )
#     order = models.ForeignKey(Order)
#     payu = models.ForeignKey(PayuDetails)
#     created_date = models.DateTimeField(
#         auto_now=True,
#         auto_now_add=True,
#         help_text="Auto generated by system")
